export * as userService from './auth/user'

export * as cartService from './commerce/cart'
export * as orderService from './commerce/order'
export * as paymentService from './commerce/payment'
export * as productService from './commerce/product'
export * as productCategoryService from './commerce/productCategory'
export * as promoCodeService from './commerce/promoCode'
export * as reviewService from './commerce/review'
export * as wishlistService from './commerce/wishlist'

export * as aboutService from './content/about'
export * as blogService from './content/blog'
export * as comingSoonContentService from './content/comingSoon'
export * as contactPageContentService from './content/contactPage'
export * as cooperationContactContentService from './content/cooperationContact'
export * as faqContentService from './content/faq'
export * as footerContentService from './content/footer'
export * as gameAccountContentService from './content/gameAccount'
export * as gameNewsContentService from './content/gameNews'
export * as homeWhyChooseUsContentService from './content/homeWhyChooseUs'
export * as privacyPolicyContentService from './content/privacyPolicy'
export * as returnPolicyContentService from './content/returnPolicy'
export * as termsContentService from './content/terms'
export * as vipContentService from './content/vip'

export * as bannerService from './marketing/banner'
export * as flashSaleService from './marketing/flashSale'
export * as widgetService from './marketing/widget'

export * as chatService from './support/chat'
export * as contactService from './support/contact'

export * as bankInfoService from './system/bankInfo'
